###
GET http://localhost:3001/api/notes/

###
GET http://localhost:3001/

###
POST http://localhost:3001/api/notes/ HTTP/1.1
content-type: application/json

{
    "name": "a test",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT",
    "content": "This has a body Mustafa has added to test his post function"
}

###
DELETE http://localhost:3001/api/notes/2
